<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HYDHTC135998L" name="Test" tests="5" failures="2" timestamp="16 Apr 2018 05:46:14 GMT" time="27.218" errors="0">
  <testcase name="login_Test_Case_05" time="1.29" classname="com.tests.testcases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.tests.testcases.login_Test_Case_05(testcases.java:184)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- login_Test_Case_05 -->
  <testcase name="login_Test_Case_04" time="1.293" classname="com.tests.testcases">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.tests.testcases.login_Test_Case_04(testcases.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- login_Test_Case_04 -->
  <testcase name="login_Test_Case_03" time="26.932" classname="com.tests.testcases"/>
  <testcase name="login_Test_Case_02" time="27.039" classname="com.tests.testcases"/>
  <testcase name="login_Test_Case_01" time="27.134" classname="com.tests.testcases"/>
</testsuite> <!-- Test -->
